"Name": getAllVppRegisteredSitesByUserId_v3,
"Parameters": (inputUserId:string, inputStateCode:string="noStateInput", inputUtilities:string="noUtilityInput", page:int=0, page_size:int=10, includeBattCap:bool=false),
"Body": {
    let utilitiesList = split(inputUtilities, ',');
    let site_ids_from_user = toscalar(getCurrentUserSiteMapping(inputUserId) | project list_site_ids);
    let vppSiteIds =
        goldAdtPropertyMinMaxLatestViewV2
        | where Id in (site_ids_from_user)
            and Key == 'isVppRegistered'
            and tolower(valueMax) == 'true'
        | join kind=leftsemi (
            goldAdtTwinEventsLatestV2
            | where Action != 'Delete'
            | project TwinId
        ) on $left.Id == $right.TwinId
        | distinct Id
    ;
    let vppSiteInfo =
        goldAdtPropertyMinMaxLatestViewV2
        | where Id in (vppSiteIds)
            and ((Key startswith "oemInfo." and Key endswith ".oemName") or Key in (dynamic(['address.stateProvince','utilityName','address.zipPostalCode','loadZone'])))
        | summarize
            state = take_anyif(valueMax, Key == 'address.stateProvince')
            ,utilityName = take_anyif(valueMax, Key == 'utilityName')
            ,zipCode = take_anyif(valueMax, Key == 'address.zipPostalCode')
            ,loadZone = take_anyif(valueMax, Key == 'loadZone')
            ,(maxOemNum, oem) = arg_max(
                iif(Key == 'oemInfo.oemName', -1,
                    iif(Key startswith "oemInfo" and Key endswith "oemName", toint(extract(@'oemInfo\.(\d+)\.oemName', 1, Key)), int(null)))
                , valueMax)
        by siteId = Id
        | where (state == inputStateCode or inputStateCode == 'noStateInput')
            and (utilityName in (utilitiesList) or utilitiesList[0] == 'noUtilityInput')
        | project-away maxOemNum
        | order by siteId asc
        | extend rnum = row_number() - 1
        | extend pgnum = rnum / page_size
    ;
    let battery_capacity =
        union
        (
            vppSiteIds
            | where includeBattCap == false
            | project siteId = Id, rated_capacity = int(null)
            | take 0
        ),
        (
            goldAdtPropertyMinMaxLatestViewV2
            | where actionMax != 'Delete'
                and includeBattCap
                and (ModelId startswith 'dtmi:qcells:device:inverter' or ModelId startswith 'dtmi:qcells:device:batt')
                and Key in ('nameplateInfo.wMaxRtg','productInfo.prodSubType','productInfo.prodType')
            | join kind=inner (
                goldAdtAllRelationshipsLatestView
                | where Action != 'Delete'
                    and includeBattCap
                    and Target in (
                        goldAdtTwinEventsLatestV2
                        | where Action != 'Delete'
                            and (ModelId startswith 'dtmi:qcells:device:inverter' or ModelId startswith 'dtmi:qcells:device:batt')
                    )
                | project siteId = Source, targetId = Target
            ) on $left.Id == $right.targetId
            | summarize
                wMaxRtg = take_anyif(valueMax, Key == 'nameplateInfo.wMaxRtg')
                ,prodSubType = take_anyif(valueMax, Key == 'productInfo.prodSubType')
                ,prodType = take_anyif(valueMax, Key == 'productInfo.prodType')
            by siteId, targetId, ModelId
            | where prodSubType != 'PVInverter'
                and (
                    (ModelId startswith "dtmi:qcells:device:inverter" and prodSubType in ('BatteryInverter','HybridInverter'))
                    or (ModelId startswith "dtmi:qcells:device:inverter" and prodType == 'Inverter')
                    or (ModelId startswith "dtmi:qcells:device:battery" and prodType == 'Battery')
                )
            | extend inverterType = coalesce(prodSubType, prodType), wMaxRtg = toint(wMaxRtg)
            | summarize arg_min(wMaxRtg, *) by siteId, ModelId, inverterType, prodSubType, prodType
            | summarize (inverterType, inverterRating) = arg_min(inverterType, wMaxRtg) by siteId, ModelId
            | summarize rated_capacity = min(inverterRating) by siteId
        )
    ;
    let paged_sites = vppSiteInfo | where pgnum == page;
    let result_data =
        paged_sites
        | join kind=leftouter (battery_capacity) on siteId
        | extend rated_capacity = case(includeBattCap, rated_capacity, int(null))
        | extend data = pack(
            'siteId', siteId
            ,'oem', oem
            ,'state', state
            ,'utility', utilityName
            ,'zip_code', zipCode
            ,'load_zone', loadZone
            ,'battery_capacity', rated_capacity
        )
    ;
    let total_count = toscalar(vppSiteInfo | summarize count());
    let page_count = toscalar(paged_sites | summarize count());
    let data_value = result_data | summarize data = make_list(data);
    let pagination_metadata = pack('pagination', pack('page', page, 'page_size', page_count, 'total_count', total_count));
    let status = iff(total_count == 0, 404, 200)
    ;
    data_value
    | extend metadata = pagination_metadata, status = status
    | project metadata, data, status
},
"Folder": API Functions,
"DocString": Get smaller set of VPP site data based on userid, state, and utility
