"""
Generate complete KQL validation query with site IDs embedded
This creates a ready-to-run KQL query for Fabric/Eventhouse
"""

import csv
from pathlib import Path

# Input file
csv_file = Path(__file__).parent / "leap_meters_export_05282026.csv"
output_file = Path(__file__).parent / "DSGS_LeapContract_Validation_READY.kql"

# Read CSV and extract site IDs
site_ids = []
with open(csv_file, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        site_id = row['Asset Registry Site ID (partner_reference)']
        if site_id:
            site_ids.append(site_id)

# Get unique site IDs (sorted)
unique_site_ids = sorted(set(site_ids))

print(f"Total enrolled sites: {len(unique_site_ids)}")

# Generate KQL query with embedded site IDs
kql_query = """// ============================================================================
// TICKET 19400: DSGS Site List Validation - Leap Contract in Asset Registry
// ============================================================================
// Purpose: Validate that all enrolled DSGS sites (May 2026) have Leap Contracts in Asset Registry
// Date: 2026-05-29
// Auto-generated by: generate_validation_query.py
//
// Task: Compare enrolled site list against Asset Registry to find sites missing Leap Contracts
// Reference CSV: leap_meters_export_05282026.csv ({total_sites} sites)
// ============================================================================

// ============================================================================
// STEP 1: Define Enrolled DSGS Site List ({total_sites} sites)
// ============================================================================

let enrolled_dsgs_sites_table = datatable(siteId:string) [
{site_id_list}
];

// ============================================================================
// STEP 2: Fetch Sites with Leap Contracts from Asset Registry
// ============================================================================

let ar_sites_with_leap = 
    goldAdtPropertyMinMaxLatestViewV2
    | where Key == 'meterId' 
      and ModelId startswith 'dtmi:qcells:contract:leapContract'  // Use startswith for version flexibility
      and tolower(actionMax) != 'delete'                           // Exclude deleted contracts
    | join kind=inner (
        goldAdtAllRelationshipsLatestView
        | where tolower(Action) != 'delete'
        | project siteId = Source, Target
    ) on $left.Id == $right.Target
    | distinct siteId, meterId = valueMax
    | extend has_leap_contract = true
;

// ============================================================================
// STEP 3: Compare and Generate Validation Results
// ============================================================================

let validation_results = 
    enrolled_dsgs_sites_table
    | join kind=leftouter (ar_sites_with_leap) on siteId
    | extend 
        leap_contract_status = case(
            isnotnull(has_leap_contract), "Has Leap Contract",
            "Missing Leap Contract"
        )
    | project siteId, meterId, leap_contract_status
    | order by leap_contract_status, siteId asc
;

// ============================================================================
// STEP 4: Summary Statistics
// ============================================================================

let enrolled_count = toscalar(enrolled_dsgs_sites_table | count);
let sites_with_leap_count = toscalar(validation_results | where leap_contract_status == "Has Leap Contract" | count);
let sites_missing_leap_count = toscalar(validation_results | where leap_contract_status == "Missing Leap Contract" | count);

// Print summary
union 
    (print Summary = "VALIDATION SUMMARY", 
           Metric = "Total Enrolled DSGS Sites", 
           Value = enrolled_count, 
           Percentage = 100.0),
    (print Summary = "", 
           Metric = "Sites WITH Leap Contract", 
           Value = sites_with_leap_count, 
           Percentage = round(sites_with_leap_count * 100.0 / enrolled_count, 2)),
    (print Summary = "", 
           Metric = "Sites MISSING Leap Contract", 
           Value = sites_missing_leap_count, 
           Percentage = round(sites_missing_leap_count * 100.0 / enrolled_count, 2))
| project Metric, Value, Percentage = strcat(tostring(Percentage), "%");

print "";
print "==============================================================================";
print "FULL VALIDATION RESULTS (All Sites)";
print "==============================================================================";

validation_results;

print "";
print "==============================================================================";
print "SITES MISSING LEAP CONTRACTS (Report to AR Team)";
print "==============================================================================";

validation_results
| where leap_contract_status == "Missing Leap Contract"
| project siteId
| order by siteId asc;

// ============================================================================
// NEXT STEPS:
// ============================================================================
// 1. Export 'SITES MISSING LEAP CONTRACTS' to CSV
// 2. Share with @Ashok Bhaskar @Chanhyup.Kim from Asset Registry team
// 3. Request them to add Leap Contracts for missing sites
// 4. Re-run this validation after AR updates
// 5. Once all sites validated, proceed with April & May 2026 data extraction
// ============================================================================
"""

# Format site IDs for KQL datatable (5 per line for readability)
site_id_lines = []
for i in range(0, len(unique_site_ids), 5):
    batch = unique_site_ids[i:i+5]
    line = "    " + ", ".join([f'"{sid}"' for sid in batch])
    if i + 5 < len(unique_site_ids):
        line += ","
    site_id_lines.append(line)

site_id_list_str = "\n".join(site_id_lines)

# Populate the template
final_query = kql_query.format(
    total_sites=len(unique_site_ids),
    site_id_list=site_id_list_str
)

# Write to file
with open(output_file, 'w', encoding='utf-8') as f:
    f.write(final_query)

print(f"✅ Generated KQL validation query: {output_file.name}")
print(f"✅ Query contains {len(unique_site_ids)} enrolled site IDs")
print(f"\nTo run validation:")
print(f"1. Open {output_file.name} in Fabric/Eventhouse")
print(f"2. Execute the query")
print(f"3. Review validation results and export missing sites")
